import GameCamera from "./gameCamera";

type CameraCommand =
  | "setOrigin"
  | "setMode"
  | "setTarget"
  | "setSmoothing"
  | "setDeadzone"
  | "setOffset"
  | "setLookahead"
  | "setAim"
  | "setPlatformLock"
  | "setGrounded"
  | "setFree"
  | "pan"
  | "setPosition"
  | "teleport"
  | "snap"
  | "getState"
  | "setState"
  | "setBounds"
  | "setZoom"
  | "zoomBy"
  | "setZoomLimits"
  | "setZoomSmoothing"
  | "setWheelZoom"
  | "setZoomLevels"
  | "getPosition"
  | "getCenter"
  | "getZoom"
  | "getZoomTarget"
  | "getBoundsZoom"
  | "getMode"
  | "getTarget"
  | "getViewBounds"
  | "worldToScreen"
  | "screenToWorld"
  | "claim"
  | "isClaimed"
  | "getClaimWeight"
  | "signals"
  | "shake"
  | "setShake"
  | "getTrauma"
  | "kick"
  | "setEffects"
  | "zoomPunch"
  | "setSway"
  | "tilt"
  | "getSwayStrength";

export const Camera: Pick<typeof GameCamera, CameraCommand> = GameCamera;
